version: '3.7'
services: 
  nginx:
    image: nginx:alpine 
    volumes: 
      - ./default.conf.template:/etc/nginx/templates/default.conf.template
    # command: envsubst < /tmp/default.conf.template > /etc/nginx/conf.d/default.conf
    environment: 
      - SERVER_PORT=80
      - SERVER_NAME=app.domain.local
    ports: 
      - 8080:80